services:
  #PostgreSQL DB
  finsync-db:
    image: postgres:16-alpine
    container_name: finsync_postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER} # <--- Lee del .env
      POSTGRES_PASSWORD: ${DB_PASSWORD} # <--- Lee del .env
      POSTGRES_DB: ${DB_NAME}        # <--- Lee del .env
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  # DB Interface
  pgadmin:
    image: dpage/pgadmin4
    container_name: finsync_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@finsync.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - finsync-db

volumes:
  postgres_data: